In [ ]:
!pip uninstall -y scikit-learn numpy
!pip install numpy==1.26.4 scikit-learn==1.3.0 --no-cache-dir
!pip uninstall -y xgboost
!pip install --no-cache-dir xgboost

Found existing installation: scikit-learn 1.6.1
Uninstalling scikit-learn-1.6.1:
  Successfully uninstalled scikit-learn-1.6.1
Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Collecting numpy==1.26.4
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.9 MB/s eta 0:00:00
Collecting scikit-learn==1.3.0
  Downloading scikit_learn-1.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.0) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.0) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.0) (3.5.0)
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 197.1 MB/s eta 0:00:00
Downloading scikit_learn-1.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 183.1 MB/s eta 0:00:00
Installing collected packages: numpy, scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-learn 0.13.0 requires scikit-learn<2,>=1.3.2, but you have scikit-learn 1.3.0 which is incompatible.
mlxtend 0.23.4 requires scikit-learn>=1.3.1, but you have scikit-learn 1.3.0 which is incompatible.
Successfully installed numpy-1.26.4 scikit-learn-1.3.0
Found existing installation: xgboost 2.1.4
Uninstalling xgboost-2.1.4:
  Successfully uninstalled xgboost-2.1.4
Collecting xgboost
  Downloading xgboost-2.1.4-py3-none-manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from xgboost) (1.26.4)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.11/dist-packages (from xgboost) (2.21.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from xgboost) (1.13.1)
Downloading xgboost-2.1.4-py3-none-manylinux_2_28_x86_64.whl (223.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 223.6/223.6 MB 168.0 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-2.1.4

In [ ]:
import numpy as np
import sklearn
import xgboost as xgb

print(f"NumPy version: {np.__version__}")
print(f"Scikit-learn version: {sklearn.__version__}")
print(f"XGBoost version: {xgb.__version__}")

NumPy version: 1.26.4
Scikit-learn version: 1.3.0
XGBoost version: 2.1.4

In [ ]:
import pandas as pd
import numpy as np
import os
import urllib.request

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
from datetime import date

#**DATA MANAGEMENT**

### 1/Import des données

In [1]:
from google.colab import drive
import pandas as pd
import os

# Monter Google Drive
drive.mount('/content/drive')

# Définir le chemin correct (notez le 'ML' en majuscules)
chemin = '/content/drive/MyDrive/Colab_data_projet_ML/'

# Chargement des fichiers CSV
df_1 = pd.read_csv(os.path.join(chemin, "temperature-quotidienne-regionale.csv"), sep=";", low_memory=False)
df_2 = pd.read_csv(os.path.join(chemin, "rayonnement-solaire-vitesse-vent-tri-horaires-regionaux.csv"), sep=";", low_memory=False)
df_3 = pd.read_csv(os.path.join(chemin, "eco2mix-regional-tr.csv"), sep=";", low_memory=False)
df_4 = pd.read_csv(os.path.join(chemin, "eco2mix-regional-cons-def.csv"), sep=";", low_memory=False)

Mounted at /content/drive

## 2/Gestion des données

###2.1 /Vérification des mois manquants pour chaque région dans les 4 **df**

In [2]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42510 entries, 0 to 42509
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 42510 non-null  object
 1   Date               42510 non-null  object
 2   Code INSEE région  42510 non-null  int64
 3   Région             42510 non-null  object
 4   TMin (°C)          42510 non-null  float64
 5   TMax (°C)          42510 non-null  float64
 6   TMoy (°C)          42510 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 2.3+ MB

In [3]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339351 entries, 0 to 339350
Data columns (total 5 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               339351 non-null  object
 1   Code INSEE région                  339351 non-null  int64
 2   Région                             339351 non-null  object
 3   Vitesse du vent à 100m (m/s)       339351 non-null  float64
 4   Rayonnement solaire global (W/m2)  339351 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.9+ MB

In [4]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 787712 entries, 0 to 787711
Data columns (total 30 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Code INSEE région    787712 non-null  int64
 1   Région               787712 non-null  object
 2   Nature               787712 non-null  object
 3   Date                 787712 non-null  object
 4   Heure                787712 non-null  object
 5   Date - Heure         787712 non-null  object
 6   Consommation (MW)    786956 non-null  float64
 7   Thermique (MW)       787265 non-null  float64
 8   Nucléaire (MW)       765191 non-null  float64
 9   Eolien (MW)          787285 non-null  float64
 10  Solaire (MW)         787284 non-null  float64
 11  Hydraulique (MW)     787269 non-null  float64
 12  Pompage (MW)         787285 non-null  object
 13  Bioénergies (MW)     787271 non-null  float64
 14  Ech. physiques (MW)  786957 non-null  float64
 15  Stockage batterie    787285 non-null  object
 16  Déstockage batterie  787285 non-null  object
 17  TCO Thermique (%)    785444 non-null  float64
 18  TCH Thermique (%)    787265 non-null  float64
 19  TCO Nucléaire (%)    763565 non-null  float64
 20  TCH Nucléaire (%)    488256 non-null  float64
 21  TCO Eolien (%)       785444 non-null  float64
 22  TCH Eolien (%)       787285 non-null  float64
 23  TCO Solaire (%)      785444 non-null  float64
 24  TCH Solaire (%)      787284 non-null  float64
 25  TCO Hydraulique (%)  785444 non-null  float64
 26  TCH Hydraulique (%)  787269 non-null  float64
 27  TCO Bioénergies (%)  785444 non-null  float64
 28  TCH Bioénergies (%)  787271 non-null  float64
 29  Column 68            0 non-null       float64
dtypes: float64(21), int64(1), object(8)
memory usage: 180.3+ MB

In [5]:
df_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2121408 entries, 0 to 2121407
Data columns (total 32 columns):
 #   Column               Dtype
---  ------               -----
 0   Code INSEE région    int64
 1   Région               object
 2   Nature               object
 3   Date                 object
 4   Heure                object
 5   Date - Heure         object
 6   Consommation (MW)    float64
 7   Thermique (MW)       float64
 8   Nucléaire (MW)       float64
 9   Eolien (MW)          object
 10  Solaire (MW)         float64
 11  Hydraulique (MW)     float64
 12  Pompage (MW)         float64
 13  Bioénergies (MW)     float64
 14  Ech. physiques (MW)  float64
 15  Stockage batterie    float64
 16  Déstockage batterie  float64
 17  Eolien terrestre     float64
 18  Eolien offshore      float64
 19  TCO Thermique (%)    float64
 20  TCH Thermique (%)    float64
 21  TCO Nucléaire (%)    float64
 22  TCH Nucléaire (%)    float64
 23  TCO Eolien (%)       float64
 24  TCH Eolien (%)       float64
 25  TCO Solaire (%)      float64
 26  TCH Solaire (%)      float64
 27  TCO Hydraulique (%)  float64
 28  TCH Hydraulique (%)  float64
 29  TCO Bioénergies (%)  float64
 30  TCH Bioénergies (%)  float64
 31  Column 30            float64
dtypes: float64(25), int64(1), object(6)
memory usage: 517.9+ MB

In [6]:
df_1["Date"]= pd.to_datetime(df_1["Date"], utc=True)
df_2["Date"]= pd.to_datetime(df_2["Date"], utc=True)
df_3["Date"]= pd.to_datetime(df_3["Date"], utc=True)
df_4["Date"]= pd.to_datetime(df_4["Date"], utc=True)

In [7]:
# Vérifier les mois manquants pour chaque région dans df_1


df_1['Year'] = df_1['Date'].dt.year
df_1['Month'] = df_1['Date'].dt.month

# Créer un dictionnaire pour stocker les mois manquants par région
missing_months_1 = {}

# Groupby par région et analyse des mois manquants
for region, group in df_1.groupby('Région'):
    months_present = set(group['Month'].unique())
    all_months = set(range(1, 13))  # Les mois de 1 à 12
    missing_months = all_months - months_present

    # Si des mois sont manquants, les ajouter au dictionnaire
    if missing_months:
        if region not in missing_months_1:
            missing_months_1[region] = {}
        for year, year_group in group.groupby('Year'):
            months_in_year = set(year_group['Month'].unique())
            missing_in_year = all_months - months_in_year
            if missing_in_year:
                missing_months_1[region][year] = missing_in_year

# Afficher les régions et les mois manquants
print(f"Régions avec des mois manquants dans df_1: {missing_months_1}")

Régions avec des mois manquants dans df_1: {}

In [8]:
# Obtenir la date minimale et maximale de la colonne 'Date' pour toutes les années
min_date = df_1['Date'].min()
max_date = df_1['Date'].max()

# Afficher les résultats
print(f"Date minimale : {min_date}")
print(f"Date maximale : {max_date}")

Date minimale : 2016-01-01 00:00:00+00:00
Date maximale : 2024-12-29 00:00:00+00:00

In [9]:
# Vérifier les mois manquants pour chaque région dans df_2


df_2['Year'] = df_2['Date'].dt.year
df_2['Month'] = df_2['Date'].dt.month

# Créer un dictionnaire pour stocker les mois manquants par région
missing_months_2 = {}

# Groupby par région et analyse des mois manquants
for region, group in df_2.groupby('Région'):
    months_present = set(group['Month'].unique())
    all_months = set(range(1, 13))  # Les mois de 1 à 12
    missing_months = all_months - months_present

    # Si des mois sont manquants, les ajouter au dictionnaire
    if missing_months:
        if region not in missing_months_2:
            missing_months_2[region] = {}
        for year, year_group in group.groupby('Year'):
            months_in_year = set(year_group['Month'].unique())
            missing_in_year = all_months - months_in_year
            if missing_in_year:
                missing_months_2[region][year] = missing_in_year

# Afficher les régions et les mois manquants
print(f"Régions avec des mois manquants dans df_2: {missing_months_2}")

Régions avec des mois manquants dans df_2: {}

In [10]:
# Obtenir la date minimale et maximale de la colonne 'Date' pour toutes les années
min_date = df_2['Date'].min()
max_date = df_2['Date'].max()

# Afficher les résultats
print(f"Date minimale : {min_date}")
print(f"Date maximale : {max_date}")

Date minimale : 2016-01-01 03:00:00+00:00
Date maximale : 2025-01-01 00:00:00+00:00

In [11]:
# Vérifier les mois manquants pour chaque région dans df_3


df_3['Year'] = df_3['Date'].dt.year
df_3['Month'] = df_3['Date'].dt.month

# Créer un dictionnaire pour stocker les mois manquants par région
missing_months_3 = {}

# Groupby par région et analyse des mois manquants
for region, group in df_3.groupby('Région'):
    months_present = set(group['Month'].unique())
    all_months = set(range(1, 13))  # Les mois de 1 à 12
    missing_months = all_months - months_present

    # Si des mois sont manquants, les ajouter au dictionnaire
    if missing_months:
        if region not in missing_months_3:
            missing_months_3[region] = {}
        for year, year_group in group.groupby('Year'):
            months_in_year = set(year_group['Month'].unique())
            missing_in_year = all_months - months_in_year
            if missing_in_year:
                missing_months_3[region][year] = missing_in_year

# Afficher les régions et les mois manquants
print(f"Régions avec des mois manquants dans df_3: {missing_months_3}")

Régions avec des mois manquants dans df_3: {'Île-de-France': {2023: {1, 9, 10, 11, 12}}}

In [12]:
# Obtenir la date minimale et maximale de la colonne 'Date' pour toutes les années
min_date = df_3['Date'].min()
max_date = df_3['Date'].max()

# Afficher les résultats
print(f"Date minimale : {min_date}")
print(f"Date maximale : {max_date}")

Date minimale : 2023-02-01 00:00:00+00:00
Date maximale : 2025-01-27 00:00:00+00:00

In [13]:
# Vérifier les mois manquants pour chaque région dans df_4
df_4['Year'] = df_4['Date'].dt.year
df_4['Month'] = df_4['Date'].dt.month

# Créer un dictionnaire pour stocker les mois manquants par région
missing_months_4 = {}

# Groupby par région et analyse des mois manquants
for region, group in df_4.groupby('Région'):
    months_present = set(group['Month'].unique())
    all_months = set(range(1, 13))  # Les mois de 1 à 12
    missing_months = all_months - months_present

    # Si des mois sont manquants, les ajouter au dictionnaire
    if missing_months:
        if region not in missing_months_4:
            missing_months_4[region] = {}
        for year, year_group in group.groupby('Year'):
            months_in_year = set(year_group['Month'].unique())
            missing_in_year = all_months - months_in_year
            if missing_in_year:
                missing_months_4[region][year] = missing_in_year

# Afficher les régions et les mois manquants
print(f"Régions avec des mois manquants dans df_4: {missing_months_4}")

Régions avec des mois manquants dans df_4: {}

In [14]:
# Obtenir la date minimale et maximale de la colonne 'Date' pour toutes les années
min_date = df_4['Date'].min()
max_date = df_4['Date'].max()

# Afficher les résultats
print(f"Date minimale : {min_date}")
print(f"Date maximale : {max_date}")

Date minimale : 2013-01-01 00:00:00+00:00
Date maximale : 2023-01-31 00:00:00+00:00

In [15]:
df_1.head()

,ID,Date,Code INSEE région,Région,TMin (°C),TMax (°C),TMoy (°C),Year,Month
0,2018-03-10T00:00:00-76,2018-03-10 00:00:00+00:00,76,Occitanie,9.48,18.55,14.02,2018,3
1,2018-03-10T00:00:00-84,2018-03-10 00:00:00+00:00,84,Auvergne-Rhône-Alpes,8.58,17.37,12.98,2018,3
2,2018-03-10T00:00:00-27,2018-03-10 00:00:00+00:00,27,Bourgogne-Franche-Comté,9.50,17.58,13.54,2018,3
3,2018-03-11T00:00:00-24,2018-03-11 00:00:00+00:00,24,Centre-Val de Loire,8.67,17.65,13.16,2018,3
4,2018-03-11T00:00:00-44,2018-03-11 00:00:00+00:00,44,Grand Est,7.70,14.36,11.03,2018,3

In [16]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339351 entries, 0 to 339350
Data columns (total 7 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               339351 non-null  datetime64[ns, UTC]
 1   Code INSEE région                  339351 non-null  int64
 2   Région                             339351 non-null  object
 3   Vitesse du vent à 100m (m/s)       339351 non-null  float64
 4   Rayonnement solaire global (W/m2)  339351 non-null  float64
 5   Year                               339351 non-null  int32
 6   Month                              339351 non-null  int32
dtypes: datetime64[ns, UTC](1), float64(2), int32(2), int64(1), object(1)
memory usage: 15.5+ MB

In [ ]:
df_2["Date_complete"] = pd.to_datetime(df_2["Date"], errors="coerce")
df_2["Date"] = df_2["Date_complete"].dt.date
df_2["Date"]= pd.to_datetime(df_2["Date"])

In [17]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339351 entries, 0 to 339350
Data columns (total 7 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               339351 non-null  datetime64[ns, UTC]
 1   Code INSEE région                  339351 non-null  int64
 2   Région                             339351 non-null  object
 3   Vitesse du vent à 100m (m/s)       339351 non-null  float64
 4   Rayonnement solaire global (W/m2)  339351 non-null  float64
 5   Year                               339351 non-null  int32
 6   Month                              339351 non-null  int32
dtypes: datetime64[ns, UTC](1), float64(2), int32(2), int64(1), object(1)
memory usage: 15.5+ MB

In [18]:
df_1

,ID,Date,Code INSEE région,Région,TMin (°C),TMax (°C),TMoy (°C),Year,Month
0,2018-03-10T00:00:00-76,2018-03-10 00:00:00+00:00,76,Occitanie,9.48,18.55,14.02,2018,3
1,2018-03-10T00:00:00-84,2018-03-10 00:00:00+00:00,84,Auvergne-Rhône-Alpes,8.58,17.37,12.98,2018,3
2,2018-03-10T00:00:00-27,2018-03-10 00:00:00+00:00,27,Bourgogne-Franche-Comté,9.50,17.58,13.54,2018,3
3,2018-03-11T00:00:00-24,2018-03-11 00:00:00+00:00,24,Centre-Val de Loire,8.67,17.65,13.16,2018,3
4,2018-03-11T00:00:00-44,2018-03-11 00:00:00+00:00,44,Grand Est,7.70,14.36,11.03,2018,3
...,...,...,...,...,...,...,...,...,...
42505,2024-12-28T00:00:00-75,2024-12-28 00:00:00+00:00,75,Nouvelle-Aquitaine,1.38,9.26,5.32,2024,12
42506,2024-12-28T00:00:00-52,2024-12-28 00:00:00+00:00,52,Pays de la Loire,0.80,4.85,2.82,2024,12
42507,2024-12-29T00:00:00-75,2024-12-29 00:00:00+00:00,75,Nouvelle-Aquitaine,1.35,8.23,4.79,2024,12
42508,2024-12-29T00:00:00-24,2024-12-29 00:00:00+00:00,24,Centre-Val de Loire,1.62,4.40,3.01,2024,12
42509,2024-12-29T00:00:00-27,2024-12-29 00:00:00+00:00,27,Bourgogne-Franche-Comté,-2.05,1.03,-0.51,2024,12

In [19]:
df_2

,Date,Code INSEE région,Région,Vitesse du vent à 100m (m/s),Rayonnement solaire global (W/m2),Year,Month
0,2016-10-11 03:00:00+00:00,84,Auvergne-Rhône-Alpes,4.10,0.00,2016,10
1,2016-10-11 03:00:00+00:00,93,Provence-Alpes-Côte d'Azur,7.56,0.00,2016,10
2,2016-10-11 06:00:00+00:00,27,Bourgogne-Franche-Comté,4.52,0.11,2016,10
3,2016-10-11 06:00:00+00:00,84,Auvergne-Rhône-Alpes,4.05,0.07,2016,10
4,2016-10-11 06:00:00+00:00,76,Occitanie,7.42,0.00,2016,10
...,...,...,...,...,...,...,...
339346,2024-12-31 21:00:00+00:00,93,Provence-Alpes-Côte d'Azur,4.08,0.00,2024,12
339347,2025-01-01 00:00:00+00:00,52,Pays de la Loire,5.87,0.00,2025,1
339348,2025-01-01 00:00:00+00:00,75,Nouvelle-Aquitaine,4.15,0.00,2025,1
339349,2025-01-01 00:00:00+00:00,44,Grand Est,4.49,0.00,2025,1
339350,2025-01-01 00:00:00+00:00,93,Provence-Alpes-Côte d'Azur,4.14,0.00,2025,1

In [20]:
df_3

,Code INSEE région,Région,Nature,Date,Heure,Date - Heure,Consommation (MW),Thermique (MW),Nucléaire (MW),Eolien (MW),...,TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Column 68,Year,Month
0,76,Occitanie,Données temps réel,2023-02-01 00:00:00+00:00,01:00,2023-02-01T01:00:00+01:00,5419.0,72.0,1246.0,765.0,...,48.33,0.0,0.0,11.48,11.77,1.97,71.81,NaN,2023,2
1,76,Occitanie,Données temps réel,2023-02-01 00:00:00+00:00,01:15,2023-02-01T01:15:00+01:00,5420.0,72.0,1247.0,744.0,...,47.00,0.0,0.0,11.88,12.18,1.96,71.14,NaN,2023,2
2,76,Occitanie,Données temps réel,2023-02-01 00:00:00+00:00,02:00,2023-02-01T02:00:00+01:00,5411.0,72.0,1247.0,694.0,...,43.84,0.0,0.0,11.86,12.15,2.03,73.83,NaN,2023,2
3,76,Occitanie,Données temps réel,2023-02-01 00:00:00+00:00,05:00,2023-02-01T05:00:00+01:00,5094.0,72.0,1243.0,767.0,...,48.45,0.0,0.0,13.68,13.19,2.06,70.47,NaN,2023,2
4,76,Occitanie,Données temps réel,2023-02-01 00:00:00+00:00,05:30,2023-02-01T05:30:00+01:00,5190.0,72.0,1247.0,766.0,...,48.39,0.0,0.0,9.71,9.53,2.00,69.80,NaN,2023,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787707,11,Île-de-France,Données temps réel,2023-08-27 00:00:00+00:00,23:15,2023-08-27T23:15:00+02:00,5638.0,29.0,0.0,15.0,...,10.34,0.0,0.0,0.28,84.21,1.84,32.60,NaN,2023,8
787708,11,Île-de-France,Données temps réel,2023-08-28 00:00:00+00:00,01:15,2023-08-28T01:15:00+02:00,4642.0,163.0,0.0,16.0,...,11.03,0.0,0.0,0.34,84.21,2.22,32.29,NaN,2023,8
787709,11,Île-de-France,Données temps réel,2023-08-28 00:00:00+00:00,02:15,2023-08-28T02:15:00+02:00,4404.0,171.0,0.0,14.0,...,9.66,0.0,0.0,0.36,84.21,2.38,32.92,NaN,2023,8
787710,11,Île-de-France,Données temps réel,2023-08-28 00:00:00+00:00,03:30,2023-08-28T03:30:00+02:00,4142.0,163.0,0.0,10.0,...,6.90,0.0,0.0,0.39,84.21,2.49,32.29,NaN,2023,8
787711,11,Île-de-France,Données temps réel,2023-08-28 00:00:00+00:00,03:45,2023-08-28T03:45:00+02:00,4152.0,163.0,0.0,9.0,...,6.21,0.0,0.0,0.39,84.21,2.48,32.29,NaN,2023,8

In [21]:
df_4

,Code INSEE région,Région,Nature,Date,Heure,Date - Heure,Consommation (MW),Thermique (MW),Nucléaire (MW),Eolien (MW),...,TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Column 30,Year,Month
0,27,Bourgogne-Franche-Comté,Données définitives,2013-01-01 00:00:00+00:00,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,1
1,93,Provence-Alpes-Côte d'Azur,Données définitives,2013-01-01 00:00:00+00:00,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,1
2,28,Normandie,Données définitives,2013-01-01 00:00:00+00:00,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,1
3,76,Occitanie,Données définitives,2013-01-01 00:00:00+00:00,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,1
4,44,Grand Est,Données définitives,2013-01-01 00:00:00+00:00,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121403,75,Nouvelle-Aquitaine,Données consolidées,2023-01-31 00:00:00+00:00,23:30,2023-01-31T23:30:00+01:00,5827.0,157.0,3651.0,44,...,2.78,0.0,0.0,5.54,14.41,1.99,35.58,NaN,2023,1
2121404,84,Auvergne-Rhône-Alpes,Données consolidées,2023-01-31 00:00:00+00:00,23:30,2023-01-31T23:30:00+01:00,8927.0,390.0,13291.0,148,...,20.47,0.0,0.0,32.90,25.76,1.25,58.64,NaN,2023,1
2121405,27,Bourgogne-Franche-Comté,Données consolidées,2023-01-31 00:00:00+00:00,23:30,2023-01-31T23:30:00+01:00,2687.0,166.0,0.0,210,...,20.45,0.0,0.0,8.19,42.07,1.82,61.25,NaN,2023,1
2121406,93,Provence-Alpes-Côte d'Azur,Données consolidées,2023-01-31 00:00:00+00:00,23:30,2023-01-31T23:30:00+01:00,6139.0,350.0,0.0,44,...,45.83,0.0,0.0,30.14,56.68,1.40,28.96,NaN,2023,1
2121407,52,Pays de la Loire,Données consolidées,2023-01-31 00:00:00+00:00,23:30,2023-01-31T23:30:00+01:00,3826.0,172.0,0.0,205,...,11.88,0.0,0.0,0.16,60.00,1.52,70.73,NaN,2023,1

## 3/Regroupement des dataset par jours

###3.1 /Le df_Rayonnement solaire et Vitesse vent (df_2) (Calcul de la moyenne des données horaires pour obtenir des valeurs journalières).

In [22]:
df_2_daily = df_2.groupby([df_2["Date"].dt.date, "Code INSEE région", "Région"])[["Vitesse du vent à 100m (m/s)", "Rayonnement solaire global (W/m2)"]].mean().reset_index()
df_2_daily["Date"]= pd.to_datetime(df_2_daily["Date"], utc=True)

In [23]:
df_2_daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42380 entries, 0 to 42379
Data columns (total 5 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               42380 non-null  datetime64[ns, UTC]
 1   Code INSEE région                  42380 non-null  int64
 2   Région                             42380 non-null  object
 3   Vitesse du vent à 100m (m/s)       42380 non-null  float64
 4   Rayonnement solaire global (W/m2)  42380 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(2), int64(1), object(1)
memory usage: 1.6+ MB

In [24]:
print(df_2_daily["Date"].dt.month.unique())

[ 1  2  3  4  5  6  7  8  9 10 11 12]

### 3.2 / df_1 : supprimer uniquement la colonnes ID (données de **la** tempérautre sont journaliers)

In [25]:
df_1 = df_1.drop(columns=["ID"])

In [26]:
df_1.dtypes

Date                 datetime64[ns, UTC]
Code INSEE région                  int64
Région                            object
TMin (°C)                        float64
TMax (°C)                        float64
TMoy (°C)                        float64
Year                               int32
Month                              int32
dtype: object

###3.3 / df_3 et df_4 (df_consommation): Agrégation des données de consommation et production énergétique

####3.3.1/Convertir les valeurs de MW en MWh

Dans le cadre de l'analyse des données de consommation et de production énergétique, il est essentiel de convertir les valeurs mesurées en mégawatts (MW) en mégawattheures (MWh) pour obtenir une représentation précise de l'énergie produite ou consommée sur une période donnée. Les valeurs en MW représentent la puissance à un instant donné, tandis que les MWh mesurent l'énergie totale sur une durée spécifique. Étant donné que les données sont collectées toutes les 30 minutes pour le df_4 et toutes les 15 min pour le df_3, chaque valeur en MW doit être multipliée par 0,5 ou 0,24  pour obtenir les valeurs en MWh

In [27]:
unique_heures_df_3 = df_3['Heure'].unique()
print("Valeurs uniques des heures dans df_3 :", unique_heures_df_3)

Valeurs uniques des heures dans df_3 : ['01:00' '01:15' '02:00' '05:00' '05:30' '05:45' '07:15' '08:15' '11:00'
 '12:15' '12:30' '13:15' '13:45' '14:45' '15:00' '17:15' '18:15' '19:00'
 '00:15' '01:30' '04:45' '06:45' '09:30' '13:00' '13:30' '16:30' '17:00'
 '17:30' '18:00' '18:45' '21:00' '22:15' '23:45' '02:15' '03:15' '04:15'
 '06:30' '08:30' '08:45' '09:45' '10:15' '11:45' '12:00' '14:15' '15:30'
 '16:15' '20:30' '22:45' '04:00' '04:30' '06:15' '10:30' '10:45' '12:45'
 '15:15' '19:45' '20:45' '21:45' '23:30' '07:45' '14:00' '14:30' '17:45'
 '20:15' '21:30' '00:30' '00:45' '09:15' '10:00' '19:15' '23:15' '11:30'
 '19:30' '21:15' '22:00' '00:00' '02:30' '09:00' '16:00' '20:00' '07:30'
 '23:00' '03:00' '07:00' '01:45' '05:15' '06:00' '08:00' '18:30' '16:45'
 '03:45' '15:45' '11:15' '02:45' '22:30' '03:30']

In [28]:
unique_heures_df_4 = df_4['Heure'].unique()
print("Valeurs uniques des heures dans df_4 :", unique_heures_df_4)

Valeurs uniques des heures dans df_4 : ['00:00' '00:30' '01:00' '01:30' '02:00' '02:30' '03:00' '03:30' '04:00'
 '04:30' '05:00' '05:30' '06:00' '06:30' '07:00' '07:30' '08:00' '08:30'
 '09:00' '09:30' '10:00' '10:30' '11:00' '11:30' '12:00' '12:30' '13:00'
 '13:30' '14:00' '14:30' '15:00' '15:30' '16:00' '16:30' '17:00' '17:30'
 '18:00' '18:30' '19:00' '19:30' '20:00' '20:30' '21:00' '21:30' '22:00'
 '22:30' '23:00' '23:30']

In [29]:



# Convertir les colonnes en types numériques
cols_to_convert = ['Consommation (MW)', 'Thermique (MW)', 'Nucléaire (MW)',
                   'Eolien (MW)', 'Solaire (MW)', 'Hydraulique (MW)', 'Bioénergies (MW)']

for col in cols_to_convert:
    df_3[col] = pd.to_numeric(df_3[col], errors='coerce')
    df_4[col] = pd.to_numeric(df_4[col], errors='coerce')

# Fonction pour convertir MW en MWh en fonction de la durée
def convertir_en_mwh(df, colonne_mw, nouvelle_colonne, duree_en_heures):
    df[nouvelle_colonne] = df[colonne_mw] * duree_en_heures

# Ajouter des colonnes pour df_3 (15 minutes = 0.25 heures)
convertir_en_mwh(df_3, 'Consommation (MW)', 'Consommation (MWh)', 0.25)
convertir_en_mwh(df_3, 'Thermique (MW)', 'Thermique (MWh)', 0.25)
convertir_en_mwh(df_3, 'Nucléaire (MW)', 'Nucléaire (MWh)', 0.25)
convertir_en_mwh(df_3, 'Eolien (MW)', 'Eolien (MWh)', 0.25)
convertir_en_mwh(df_3, 'Solaire (MW)', 'Solaire (MWh)', 0.25)
convertir_en_mwh(df_3, 'Hydraulique (MW)', 'Hydraulique (MWh)', 0.25)
convertir_en_mwh(df_3, 'Bioénergies (MW)', 'Bioénergies (MWh)', 0.25)

# Ajouter des colonnes pour df_4 (30 minutes = 0.5 heures)
convertir_en_mwh(df_4, 'Consommation (MW)', 'Consommation (MWh)', 0.5)
convertir_en_mwh(df_4, 'Thermique (MW)', 'Thermique (MWh)', 0.5)
convertir_en_mwh(df_4, 'Nucléaire (MW)', 'Nucléaire (MWh)', 0.5)
convertir_en_mwh(df_4, 'Eolien (MW)', 'Eolien (MWh)', 0.5)
convertir_en_mwh(df_4, 'Solaire (MW)', 'Solaire (MWh)', 0.5)
convertir_en_mwh(df_4, 'Hydraulique (MW)', 'Hydraulique (MWh)', 0.5)
convertir_en_mwh(df_4, 'Bioénergies (MW)', 'Bioénergies (MWh)', 0.5)

# Afficher les premières lignes des DataFrames pour vérifier les nouvelles colonnes
print(df_3.head())
print(df_4.head())

   Code INSEE région     Région              Nature                      Date  \
0                 76  Occitanie  Données temps réel 2023-02-01 00:00:00+00:00
1                 76  Occitanie  Données temps réel 2023-02-01 00:00:00+00:00
2                 76  Occitanie  Données temps réel 2023-02-01 00:00:00+00:00
3                 76  Occitanie  Données temps réel 2023-02-01 00:00:00+00:00
4                 76  Occitanie  Données temps réel 2023-02-01 00:00:00+00:00

   Heure               Date - Heure  Consommation (MW)  Thermique (MW)  \
0  01:00  2023-02-01T01:00:00+01:00             5419.0            72.0
1  01:15  2023-02-01T01:15:00+01:00             5420.0            72.0
2  02:00  2023-02-01T02:00:00+01:00             5411.0            72.0
3  05:00  2023-02-01T05:00:00+01:00             5094.0            72.0
4  05:30  2023-02-01T05:30:00+01:00             5190.0            72.0

   Nucléaire (MW)  Eolien (MW)  ...  Column 68  Year Month  \
0          1246.0        765.0  ...        NaN  2023     2
1          1247.0        744.0  ...        NaN  2023     2
2          1247.0        694.0  ...        NaN  2023     2
3          1243.0        767.0  ...        NaN  2023     2
4          1247.0        766.0  ...        NaN  2023     2

   Consommation (MWh)  Thermique (MWh) Nucléaire (MWh) Eolien (MWh)  \
0             1354.75             18.0          311.50       191.25
1             1355.00             18.0          311.75       186.00
2             1352.75             18.0          311.75       173.50
3             1273.50             18.0          310.75       191.75
4             1297.50             18.0          311.75       191.50

   Solaire (MWh)  Hydraulique (MWh)  Bioénergies (MWh)
0            0.0             155.50              26.75
1            0.0             161.00              26.50
2            0.0             160.50              27.50
3            0.0             174.25              26.25
4            0.0             126.00              26.00

[5 rows x 39 columns]
   Code INSEE région                      Région               Nature  \
0                 27     Bourgogne-Franche-Comté  Données définitives
1                 93  Provence-Alpes-Côte d'Azur  Données définitives
2                 28                   Normandie  Données définitives
3                 76                   Occitanie  Données définitives
4                 44                   Grand Est  Données définitives

                       Date  Heure               Date - Heure  \
0 2013-01-01 00:00:00+00:00  00:00  2013-01-01T00:00:00+01:00
1 2013-01-01 00:00:00+00:00  00:00  2013-01-01T00:00:00+01:00
2 2013-01-01 00:00:00+00:00  00:00  2013-01-01T00:00:00+01:00
3 2013-01-01 00:00:00+00:00  00:00  2013-01-01T00:00:00+01:00
4 2013-01-01 00:00:00+00:00  00:00  2013-01-01T00:00:00+01:00

   Consommation (MW)  Thermique (MW)  Nucléaire (MW)  Eolien (MW)  ...  \
0                NaN             NaN             NaN          NaN  ...
1                NaN             NaN             NaN          NaN  ...
2                NaN             NaN             NaN          NaN  ...
3                NaN             NaN             NaN          NaN  ...
4                NaN             NaN             NaN          NaN  ...

   Column 30  Year  Month  Consommation (MWh)  Thermique (MWh)  \
0        NaN  2013      1                 NaN              NaN
1        NaN  2013      1                 NaN              NaN
2        NaN  2013      1                 NaN              NaN
3        NaN  2013      1                 NaN              NaN
4        NaN  2013      1                 NaN              NaN

   Nucléaire (MWh)  Eolien (MWh)  Solaire (MWh)  Hydraulique (MWh)  \
0              NaN           NaN            NaN                NaN
1              NaN           NaN            NaN                NaN
2              NaN           NaN            NaN                NaN
3              NaN           NaN            NaN                NaN
4              NaN           NaN            NaN                NaN

   Bioénergies (MWh)
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN

[5 rows x 41 columns]

In [30]:
df_3.columns

Index(['Code INSEE région', 'Région', 'Nature', 'Date', 'Heure',
       'Date - Heure', 'Consommation (MW)', 'Thermique (MW)', 'Nucléaire (MW)',
       'Eolien (MW)', 'Solaire (MW)', 'Hydraulique (MW)', 'Pompage (MW)',
       'Bioénergies (MW)', 'Ech. physiques (MW)', 'Stockage batterie',
       'Déstockage batterie', 'TCO Thermique (%)', 'TCH Thermique (%)',
       'TCO Nucléaire (%)', 'TCH Nucléaire (%)', 'TCO Eolien (%)',
       'TCH Eolien (%)', 'TCO Solaire (%)', 'TCH Solaire (%)',
       'TCO Hydraulique (%)', 'TCH Hydraulique (%)', 'TCO Bioénergies (%)',
       'TCH Bioénergies (%)', 'Column 68', 'Year', 'Month',
       'Consommation (MWh)', 'Thermique (MWh)', 'Nucléaire (MWh)',
       'Eolien (MWh)', 'Solaire (MWh)', 'Hydraulique (MWh)',
       'Bioénergies (MWh)'],
      dtype='object')

In [31]:
df_4.columns

Index(['Code INSEE région', 'Région', 'Nature', 'Date', 'Heure',
       'Date - Heure', 'Consommation (MW)', 'Thermique (MW)', 'Nucléaire (MW)',
       'Eolien (MW)', 'Solaire (MW)', 'Hydraulique (MW)', 'Pompage (MW)',
       'Bioénergies (MW)', 'Ech. physiques (MW)', 'Stockage batterie',
       'Déstockage batterie', 'Eolien terrestre', 'Eolien offshore',
       'TCO Thermique (%)', 'TCH Thermique (%)', 'TCO Nucléaire (%)',
       'TCH Nucléaire (%)', 'TCO Eolien (%)', 'TCH Eolien (%)',
       'TCO Solaire (%)', 'TCH Solaire (%)', 'TCO Hydraulique (%)',
       'TCH Hydraulique (%)', 'TCO Bioénergies (%)', 'TCH Bioénergies (%)',
       'Column 30', 'Year', 'Month', 'Consommation (MWh)', 'Thermique (MWh)',
       'Nucléaire (MWh)', 'Eolien (MWh)', 'Solaire (MWh)', 'Hydraulique (MWh)',
       'Bioénergies (MWh)'],
      dtype='object')

In [32]:
df_3_test= df_3.drop(columns=['Consommation (MW)', 'Thermique (MW)', 'Nucléaire (MW)',
       'Eolien (MW)', 'Solaire (MW)', 'Hydraulique (MW)', 'Pompage (MW)',
       'Bioénergies (MW)', 'Ech. physiques (MW)', 'Stockage batterie',
       'Déstockage batterie', 'TCO Thermique (%)', 'TCH Thermique (%)',
       'TCO Nucléaire (%)', 'TCH Nucléaire (%)', 'TCO Eolien (%)',
       'TCH Eolien (%)', 'TCO Solaire (%)', 'TCH Solaire (%)',
       'TCO Hydraulique (%)', 'TCH Hydraulique (%)', 'TCO Bioénergies (%)',
       'TCH Bioénergies (%)', 'Column 68', 'Year', 'Month'])

In [33]:
df_3_test

,Code INSEE région,Région,Nature,Date,Heure,Date - Heure,Consommation (MWh),Thermique (MWh),Nucléaire (MWh),Eolien (MWh),Solaire (MWh),Hydraulique (MWh),Bioénergies (MWh)
0,76,Occitanie,Données temps réel,2023-02-01 00:00:00+00:00,01:00,2023-02-01T01:00:00+01:00,1354.75,18.00,311.50,191.25,0.0,155.50,26.75
1,76,Occitanie,Données temps réel,2023-02-01 00:00:00+00:00,01:15,2023-02-01T01:15:00+01:00,1355.00,18.00,311.75,186.00,0.0,161.00,26.50
2,76,Occitanie,Données temps réel,2023-02-01 00:00:00+00:00,02:00,2023-02-01T02:00:00+01:00,1352.75,18.00,311.75,173.50,0.0,160.50,27.50
3,76,Occitanie,Données temps réel,2023-02-01 00:00:00+00:00,05:00,2023-02-01T05:00:00+01:00,1273.50,18.00,310.75,191.75,0.0,174.25,26.25
4,76,Occitanie,Données temps réel,2023-02-01 00:00:00+00:00,05:30,2023-02-01T05:30:00+01:00,1297.50,18.00,311.75,191.50,0.0,126.00,26.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
787707,11,Île-de-France,Données temps réel,2023-08-27 00:00:00+00:00,23:15,2023-08-27T23:15:00+02:00,1409.50,7.25,0.00,3.75,0.0,4.00,26.00
787708,11,Île-de-France,Données temps réel,2023-08-28 00:00:00+00:00,01:15,2023-08-28T01:15:00+02:00,1160.50,40.75,0.00,4.00,0.0,4.00,25.75
787709,11,Île-de-France,Données temps réel,2023-08-28 00:00:00+00:00,02:15,2023-08-28T02:15:00+02:00,1101.00,42.75,0.00,3.50,0.0,4.00,26.25
787710,11,Île-de-France,Données temps réel,2023-08-28 00:00:00+00:00,03:30,2023-08-28T03:30:00+02:00,1035.50,40.75,0.00,2.50,0.0,4.00,25.75
787711,11,Île-de-France,Données temps réel,2023-08-28 00:00:00+00:00,03:45,2023-08-28T03:45:00+02:00,1038.00,40.75,0.00,2.25,0.0,4.00,25.75

In [34]:
df_4_test= df_4.drop(columns=['Consommation (MW)', 'Thermique (MW)', 'Nucléaire (MW)',
       'Eolien (MW)', 'Solaire (MW)', 'Hydraulique (MW)', 'Pompage (MW)',
       'Bioénergies (MW)', 'Ech. physiques (MW)', 'Stockage batterie',
       'Déstockage batterie', 'Eolien terrestre', 'Eolien offshore',
       'TCO Thermique (%)', 'TCH Thermique (%)', 'TCO Nucléaire (%)',
       'TCH Nucléaire (%)', 'TCO Eolien (%)', 'TCH Eolien (%)',
       'TCO Solaire (%)', 'TCH Solaire (%)', 'TCO Hydraulique (%)',
       'TCH Hydraulique (%)', 'TCO Bioénergies (%)', 'TCH Bioénergies (%)',
       'Column 30', 'Year', 'Month'])

In [35]:
df_4_test

,Code INSEE région,Région,Nature,Date,Heure,Date - Heure,Consommation (MWh),Thermique (MWh),Nucléaire (MWh),Eolien (MWh),Solaire (MWh),Hydraulique (MWh),Bioénergies (MWh)
0,27,Bourgogne-Franche-Comté,Données définitives,2013-01-01 00:00:00+00:00,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93,Provence-Alpes-Côte d'Azur,Données définitives,2013-01-01 00:00:00+00:00,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28,Normandie,Données définitives,2013-01-01 00:00:00+00:00,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,76,Occitanie,Données définitives,2013-01-01 00:00:00+00:00,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,44,Grand Est,Données définitives,2013-01-01 00:00:00+00:00,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121403,75,Nouvelle-Aquitaine,Données consolidées,2023-01-31 00:00:00+00:00,23:30,2023-01-31T23:30:00+01:00,2913.5,78.5,1825.5,22.0,0.0,161.5,58.0
2121404,84,Auvergne-Rhône-Alpes,Données consolidées,2023-01-31 00:00:00+00:00,23:30,2023-01-31T23:30:00+01:00,4463.5,195.0,6645.5,74.0,0.0,1468.5,56.0
2121405,27,Bourgogne-Franche-Comté,Données consolidées,2023-01-31 00:00:00+00:00,23:30,2023-01-31T23:30:00+01:00,1343.5,83.0,0.0,105.0,0.0,110.0,24.5
2121406,93,Provence-Alpes-Côte d'Azur,Données consolidées,2023-01-31 00:00:00+00:00,23:30,2023-01-31T23:30:00+01:00,3069.5,175.0,0.0,22.0,0.0,925.0,43.0
2121407,52,Pays de la Loire,Données consolidées,2023-01-31 00:00:00+00:00,23:30,2023-01-31T23:30:00+01:00,1913.0,86.0,0.0,102.5,0.0,3.0,29.0

####3.3.2/ Agrégation de la Production et de la Consommation Énergétique par Date et Région : Somme Totale

Dans cette étape, nous effectuons une agrégation quotidienne par région en sommant à la fois la consommation et la production d'énergie. Cela nous permet d'obtenir une vue d'ensemble des totaux énergétiques par région pour chaque jour, facilitant ainsi l'analyse des tendances de consommation et de production

In [36]:
df_3_daily = df_3_test.groupby([df_3_test["Date"].dt.date, "Code INSEE région", "Région"]).apply(lambda x: x.select_dtypes("float64").sum()).reset_index()
df_4_daily = df_4_test.groupby([df_4_test["Date"].dt.date, "Code INSEE région", "Région"]).apply(lambda x: x.select_dtypes("float64").sum()).reset_index()

<ipython-input-36-52850204e4f8>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_3_daily = df_3_test.groupby([df_3_test["Date"].dt.date, "Code INSEE région", "Région"]).apply(lambda x: x.select_dtypes("float64").sum()).reset_index()
<ipython-input-36-52850204e4f8>:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_4_daily = df_4_test.groupby([df_4_test["Date"].dt.date, "Code INSEE région", "Région"]).apply(lambda x: x.select_dtypes("float64").sum()).reset_index()

In [37]:
df_3_daily.columns

Index(['Date', 'Code INSEE région', 'Région', 'Consommation (MWh)',
       'Thermique (MWh)', 'Nucléaire (MWh)', 'Eolien (MWh)', 'Solaire (MWh)',
       'Hydraulique (MWh)', 'Bioénergies (MWh)'],
      dtype='object')

In [38]:
df_4_daily.columns

Index(['Date', 'Code INSEE région', 'Région', 'Consommation (MWh)',
       'Thermique (MWh)', 'Nucléaire (MWh)', 'Eolien (MWh)', 'Solaire (MWh)',
       'Hydraulique (MWh)', 'Bioénergies (MWh)'],
      dtype='object')

In [39]:
df_3_daily.dtypes

Date                   object
Code INSEE région       int64
Région                 object
Consommation (MWh)    float64
Thermique (MWh)       float64
Nucléaire (MWh)       float64
Eolien (MWh)          float64
Solaire (MWh)         float64
Hydraulique (MWh)     float64
Bioénergies (MWh)     float64
dtype: object

In [40]:
df_4_daily.dtypes

Date                   object
Code INSEE région       int64
Région                 object
Consommation (MWh)    float64
Thermique (MWh)       float64
Nucléaire (MWh)       float64
Eolien (MWh)          float64
Solaire (MWh)         float64
Hydraulique (MWh)     float64
Bioénergies (MWh)     float64
dtype: object

In [41]:
#Conversion des colonnes "Date" en format datetime avec timezone UTC
df_3_daily["Date"]= pd.to_datetime(df_3_daily["Date"], utc=True)
df_4_daily["Date"]= pd.to_datetime(df_4_daily["Date"], utc=True)

In [42]:
df_3_daily

,Date,Code INSEE région,Région,Consommation (MWh),Thermique (MWh),Nucléaire (MWh),Eolien (MWh),Solaire (MWh),Hydraulique (MWh),Bioénergies (MWh)
0,2023-02-01 00:00:00+00:00,11,Île-de-France,234572.25,10156.25,0.00,1147.00,331.75,144.00,4017.75
1,2023-02-01 00:00:00+00:00,24,Centre-Val de Loire,64525.00,2208.00,221105.75,9021.50,810.00,210.25,1032.00
2,2023-02-01 00:00:00+00:00,27,Bourgogne-Franche-Comté,69667.75,4275.25,0.00,5437.00,796.75,4198.75,552.00
3,2023-02-01 00:00:00+00:00,28,Normandie,90391.50,9929.00,151532.75,10164.25,400.50,336.00,940.25
4,2023-02-01 00:00:00+00:00,32,Hauts-de-France,156846.75,40580.25,102370.50,70004.25,756.50,48.00,2956.25
...,...,...,...,...,...,...,...,...,...,...
8201,2025-01-27 00:00:00+00:00,53,Bretagne,45402.25,4342.50,0.00,19370.25,671.75,463.50,305.00
8202,2025-01-27 00:00:00+00:00,75,Nouvelle-Aquitaine,74416.00,1575.00,60878.50,22260.25,4526.00,3752.75,421.50
8203,2025-01-27 00:00:00+00:00,76,Occitanie,68193.50,1317.25,16867.00,3350.50,3202.75,13448.50,2660.75
8204,2025-01-27 00:00:00+00:00,84,Auvergne-Rhône-Alpes,112498.75,1863.50,117502.75,6505.75,1974.25,42572.75,544.25
8205,2025-01-27 00:00:00+00:00,93,Provence-Alpes-Côte d'Azur,63347.00,1259.50,0.00,1158.25,1199.75,13109.00,1203.00

###3.4 /Filtrage des données pour garder que les années 2016 à 2024

In [43]:
#Filtrage des données pour garder que les années 2016 à 2024

df_1 = df_1[df_1["Date"].dt.year != 2025]
df_2_daily = df_2_daily[df_2_daily["Date"].dt.year != 2025]
df_3_daily = df_3_daily[df_3_daily["Date"].dt.year != 2025]
df_4_daily = df_4_daily[~df_4_daily["Date"].dt.year.isin([2013, 2014, 2015])]

In [44]:
print(df_1["Date"].dt.year.unique())
print(df_2_daily["Date"].dt.year.unique())
print(df_3_daily["Date"].dt.year.unique())
print(df_4_daily["Date"].dt.year.unique())

[2018 2019 2016 2017 2020 2021 2022 2023 2024]
[2016 2017 2018 2019 2020 2021 2022 2023 2024]
[2023 2024]
[2016 2017 2018 2019 2020 2021 2022 2023]

## 4/Merge de tous les datasets

In [45]:
df_conso = pd.concat([df_4_daily, df_3_daily], axis=0, ignore_index=True)
df_conso

,Date,Code INSEE région,Région,Consommation (MWh),Thermique (MWh),Nucléaire (MWh),Eolien (MWh),Solaire (MWh),Hydraulique (MWh),Bioénergies (MWh)
0,2016-01-01 00:00:00+00:00,11,Île-de-France,199592.00,7386.50,0.00,191.50,27.50,235.50,3545.50
1,2016-01-01 00:00:00+00:00,24,Centre-Val de Loire,51985.50,1688.00,271526.50,6637.50,195.50,24.00,1190.50
2,2016-01-01 00:00:00+00:00,27,Bourgogne-Franche-Comté,56191.50,2677.50,0.00,2279.00,244.50,1009.00,412.00
3,2016-01-01 00:00:00+00:00,28,Normandie,77430.50,8127.00,152274.50,5268.50,52.50,394.00,1174.50
4,2016-01-01 00:00:00+00:00,32,Hauts-de-France,131545.50,12886.00,125341.00,17252.00,116.50,52.50,2965.00
...,...,...,...,...,...,...,...,...,...,...
38960,2024-12-31 00:00:00+00:00,53,Bretagne,68219.00,318.00,0.00,19678.75,479.50,1801.25,480.00
38961,2024-12-31 00:00:00+00:00,75,Nouvelle-Aquitaine,150569.50,2228.25,119770.75,2213.25,5408.00,9476.50,672.75
38962,2024-12-31 00:00:00+00:00,76,Occitanie,147090.00,2267.50,62640.00,1521.50,7082.00,42349.25,5038.50
38963,2024-12-31 00:00:00+00:00,84,Auvergne-Rhône-Alpes,218530.75,3437.25,271239.00,1136.25,4486.00,76309.75,957.50
38964,2024-12-31 00:00:00+00:00,93,Provence-Alpes-Côte d'Azur,133692.75,12152.00,0.00,11.75,5506.75,25307.00,1911.00

In [46]:
# Compter le nombre de valeurs manquantes (NaN) par colonne pour le df_conso
missing_values_count = df_conso.isna().sum()
print(missing_values_count)

Date                  0
Code INSEE région     0
Région                0
Consommation (MWh)    0
Thermique (MWh)       0
Nucléaire (MWh)       0
Eolien (MWh)          0
Solaire (MWh)         0
Hydraulique (MWh)     0
Bioénergies (MWh)     0
dtype: int64

In [47]:
# Compter le nombre de valeurs manquantes (NaN) par colonne pour df_1 (température) et df_2_daily (rayonnement solaire)
missing_values_count_temp = df_1.isna().sum()
missing_values_count_rayonn = df_2_daily.isna().sum()

# Affichage des résultats de manière plus lisible
print("Valeurs manquantes dans df_1 (température) :")
print(missing_values_count_temp)
print("\nValeurs manquantes dans df_2_daily (rayonnement solaire) :")
print(missing_values_count_rayonn)

Valeurs manquantes dans df_1 (température) :
Date                 0
Code INSEE région    0
Région               0
TMin (°C)            0
TMax (°C)            0
TMoy (°C)            0
Year                 0
Month                0
dtype: int64

Valeurs manquantes dans df_2_daily (rayonnement solaire) :
Date                                 0
Code INSEE région                    0
Région                               0
Vitesse du vent à 100m (m/s)         0
Rayonnement solaire global (W/m2)    0
dtype: int64

In [48]:
df_full = df_conso.merge(df_1, on=["Date", "Code INSEE région", "Région"], how='left') \
              .merge(df_2_daily, on=["Date", "Code INSEE région", "Région"], how='left')

In [49]:
df_full

,Date,Code INSEE région,Région,Consommation (MWh),Thermique (MWh),Nucléaire (MWh),Eolien (MWh),Solaire (MWh),Hydraulique (MWh),Bioénergies (MWh),TMin (°C),TMax (°C),TMoy (°C),Year,Month,Vitesse du vent à 100m (m/s),Rayonnement solaire global (W/m2)
0,2016-01-01 00:00:00+00:00,11,Île-de-France,199592.00,7386.50,0.00,191.50,27.50,235.50,3545.50,3.30,8.76,6.03,2016.0,1.0,8.842857,44.570000
1,2016-01-01 00:00:00+00:00,24,Centre-Val de Loire,51985.50,1688.00,271526.50,6637.50,195.50,24.00,1190.50,1.52,10.73,6.12,2016.0,1.0,9.200000,41.425714
2,2016-01-01 00:00:00+00:00,27,Bourgogne-Franche-Comté,56191.50,2677.50,0.00,2279.00,244.50,1009.00,412.00,2.22,9.52,5.87,2016.0,1.0,6.178571,43.897143
3,2016-01-01 00:00:00+00:00,28,Normandie,77430.50,8127.00,152274.50,5268.50,52.50,394.00,1174.50,2.78,9.40,6.09,2016.0,1.0,10.808571,23.730000
4,2016-01-01 00:00:00+00:00,32,Hauts-de-France,131545.50,12886.00,125341.00,17252.00,116.50,52.50,2965.00,1.72,7.72,4.72,2016.0,1.0,8.911429,37.291429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38960,2024-12-31 00:00:00+00:00,53,Bretagne,68219.00,318.00,0.00,19678.75,479.50,1801.25,480.00,NaN,NaN,NaN,NaN,NaN,6.205000,38.075000
38961,2024-12-31 00:00:00+00:00,75,Nouvelle-Aquitaine,150569.50,2228.25,119770.75,2213.25,5408.00,9476.50,672.75,NaN,NaN,NaN,NaN,NaN,4.331250,66.567500
38962,2024-12-31 00:00:00+00:00,76,Occitanie,147090.00,2267.50,62640.00,1521.50,7082.00,42349.25,5038.50,NaN,NaN,NaN,NaN,NaN,4.507500,73.131250
38963,2024-12-31 00:00:00+00:00,84,Auvergne-Rhône-Alpes,218530.75,3437.25,271239.00,1136.25,4486.00,76309.75,957.50,NaN,NaN,NaN,NaN,NaN,3.120000,77.985000
38964,2024-12-31 00:00:00+00:00,93,Provence-Alpes-Côte d'Azur,133692.75,12152.00,0.00,11.75,5506.75,25307.00,1911.00,NaN,NaN,NaN,NaN,NaN,4.303750,78.587500

In [50]:
df_full.columns

Index(['Date', 'Code INSEE région', 'Région', 'Consommation (MWh)',
       'Thermique (MWh)', 'Nucléaire (MWh)', 'Eolien (MWh)', 'Solaire (MWh)',
       'Hydraulique (MWh)', 'Bioénergies (MWh)', 'TMin (°C)', 'TMax (°C)',
       'TMoy (°C)', 'Year', 'Month', 'Vitesse du vent à 100m (m/s)',
       'Rayonnement solaire global (W/m2)'],
      dtype='object')

Les colonnes Year et Mois proviennent des 2 df météo. Ces colonnes ont été créées après le merge avec le DataFrame de consommation (df_conso).

In [51]:
df_full = df_full.drop(columns=["Year", "Month"])

In [52]:
df_full["Code INSEE région"] = df_full["Code INSEE région"].astype(str)

In [53]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38965 entries, 0 to 38964
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               38965 non-null  datetime64[ns, UTC]
 1   Code INSEE région                  38965 non-null  object
 2   Région                             38965 non-null  object
 3   Consommation (MWh)                 38965 non-null  float64
 4   Thermique (MWh)                    38965 non-null  float64
 5   Nucléaire (MWh)                    38965 non-null  float64
 6   Eolien (MWh)                       38965 non-null  float64
 7   Solaire (MWh)                      38965 non-null  float64
 8   Hydraulique (MWh)                  38965 non-null  float64
 9   Bioénergies (MWh)                  38965 non-null  float64
 10  TMin (°C)                          38762 non-null  float64
 11  TMax (°C)                          38762 non-null  float64
 12  TMoy (°C)                          38762 non-null  float64
 13  Vitesse du vent à 100m (m/s)       38617 non-null  float64
 14  Rayonnement solaire global (W/m2)  38617 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(12), object(2)
memory usage: 4.5+ MB

In [54]:
print(df_full["Date"].dt.year.unique())

[2016 2017 2018 2019 2020 2021 2022 2023 2024]

In [55]:
print(df_full.head())

                       Date Code INSEE région                   Région  \
0 2016-01-01 00:00:00+00:00                11            Île-de-France
1 2016-01-01 00:00:00+00:00                24      Centre-Val de Loire
2 2016-01-01 00:00:00+00:00                27  Bourgogne-Franche-Comté
3 2016-01-01 00:00:00+00:00                28                Normandie
4 2016-01-01 00:00:00+00:00                32          Hauts-de-France

   Consommation (MWh)  Thermique (MWh)  Nucléaire (MWh)  Eolien (MWh)  \
0            199592.0           7386.5              0.0         191.5
1             51985.5           1688.0         271526.5        6637.5
2             56191.5           2677.5              0.0        2279.0
3             77430.5           8127.0         152274.5        5268.5
4            131545.5          12886.0         125341.0       17252.0

   Solaire (MWh)  Hydraulique (MWh)  Bioénergies (MWh)  TMin (°C)  TMax (°C)  \
0           27.5              235.5             3545.5       3.30       8.76
1          195.5               24.0             1190.5       1.52      10.73
2          244.5             1009.0              412.0       2.22       9.52
3           52.5              394.0             1174.5       2.78       9.40
4          116.5               52.5             2965.0       1.72       7.72

   TMoy (°C)  Vitesse du vent à 100m (m/s)  Rayonnement solaire global (W/m2)
0       6.03                      8.842857                          44.570000
1       6.12                      9.200000                          41.425714
2       5.87                      6.178571                          43.897143
3       6.09                     10.808571                          23.730000
4       4.72                      8.911429                          37.291429

##5/Gestion des données manquantes

In [56]:
# Compter le nombre de valeurs manquantes (NaN) par colonne
missing_values_count = df_full.isna().sum()
print(missing_values_count)

Date                                   0
Code INSEE région                      0
Région                                 0
Consommation (MWh)                     0
Thermique (MWh)                        0
Nucléaire (MWh)                        0
Eolien (MWh)                           0
Solaire (MWh)                          0
Hydraulique (MWh)                      0
Bioénergies (MWh)                      0
TMin (°C)                            203
TMax (°C)                            203
TMoy (°C)                            203
Vitesse du vent à 100m (m/s)         348
Rayonnement solaire global (W/m2)    348
dtype: int64

###4.1/ Variables météo :Rayonnement solaire et vent et temp: 	Imputer par la médiane (un jour avant un jour après / 2 jours avant et 2 jours après)

In [57]:
# Liste des colonnes météo à traiter (température, rayonnement solaire, vitesse du vent)
meteo_columns = [
    "TMin (°C)", "TMax (°C)", "TMoy (°C)",
    "Rayonnement solaire global (W/m2)", "Vitesse du vent à 100m (m/s)"
]

# Appliquer l'imputation dans l'ordre : 1 jour avant, 1 jour après
for column in meteo_columns:
    df_full[column] = df_full.groupby("Code INSEE région")[column].transform(
        lambda x: x.fillna(
            # D'abord imputer avec 1 jour avant et 1 jour après
            pd.concat([x.shift(1), x.shift(-1)]).median()
        )
    )

    # Ensuite, une fois que les NaN sont remplis avec les 1 jour avant et après, on utilise 2 jours avant et après
    df_full[column] = df_full.groupby("Code INSEE région")[column].transform(
        lambda x: x.fillna(
            # Puis imputer avec 2 jours avant et 2 jours après (si encore des NaN après la première étape)
            pd.concat([x.shift(2), x.shift(-2)]).median()
        )
    )

# Vérifier le nombre de valeurs manquantes dans chaque colonne après l'imputation
for column in meteo_columns:
    missing_values = df_full[column].isna().sum()
    print(f"Nombre de valeurs manquantes dans la colonne '{column}': {missing_values}")

Nombre de valeurs manquantes dans la colonne 'TMin (°C)': 0
Nombre de valeurs manquantes dans la colonne 'TMax (°C)': 0
Nombre de valeurs manquantes dans la colonne 'TMoy (°C)': 0
Nombre de valeurs manquantes dans la colonne 'Rayonnement solaire global (W/m2)': 0
Nombre de valeurs manquantes dans la colonne 'Vitesse du vent à 100m (m/s)': 0

Nb.Le code d'abord remplit les valeurs manquantes avec les jours les plus proches (1 jour avant et 1 jour après).
Si certaines valeurs restent manquantes après cette première étape, il passe à l'utilisation des données des 2 jours avant et après.

In [58]:
df_full.isna().sum()

Date                                 0
Code INSEE région                    0
Région                               0
Consommation (MWh)                   0
Thermique (MWh)                      0
Nucléaire (MWh)                      0
Eolien (MWh)                         0
Solaire (MWh)                        0
Hydraulique (MWh)                    0
Bioénergies (MWh)                    0
TMin (°C)                            0
TMax (°C)                            0
TMoy (°C)                            0
Vitesse du vent à 100m (m/s)         0
Rayonnement solaire global (W/m2)    0
dtype: int64

## 6/ Harmonisation des données

In [59]:
# Vérifier le nombre de dates uniques par région dans df_full

# Groupby par "Région" et compter les dates uniques
nb_dates_par_region_full = df_full.groupby("Région")["Date"].nunique()

# Afficher les résultats
print(f"Nombre de dates uniques par région dans df_full:\n{nb_dates_par_region_full}")

Nombre de dates uniques par région dans df_full:
Région
Auvergne-Rhône-Alpes          3288
Bourgogne-Franche-Comté       3288
Bretagne                      3288
Centre-Val de Loire           3288
Grand Est                     3288
Hauts-de-France               3288
Normandie                     3288
Nouvelle-Aquitaine            3288
Occitanie                     3288
Pays de la Loire              3288
Provence-Alpes-Côte d'Azur    3288
Île-de-France                 2797
Name: Date, dtype: int64

In [60]:
#Dates minimum et maximum de la région "Île-de-France"

# Filtrer les données pour la région "Île-de-France"
ile_de_france = df_full[df_full["Région"] == "Île-de-France"]

# Calculer la date minimale et maximale
date_min_ile_de_france = ile_de_france["Date"].min()
date_max_ile_de_france = ile_de_france["Date"].max()

# Afficher les résultats
print(f"Date minimale en Île-de-France : {date_min_ile_de_france}")
print(f"Date maximale en Île-de-France : {date_max_ile_de_france}")

Date minimale en Île-de-France : 2016-01-01 00:00:00+00:00
Date maximale en Île-de-France : 2023-08-28 00:00:00+00:00

In [61]:
#Filtrer le df_full
## Définir les dates minimale et maximale
date_min = '2016-01-01 00:00:00+00:00'
date_max = '2023-08-28 00:00:00+00:00'

# Filtrer le DataFrame df_full
df_full_filtered = df_full[(df_full['Date'] >= date_min) & (df_full['Date'] <= date_max)]

In [62]:
df_full_filtered

,Date,Code INSEE région,Région,Consommation (MWh),Thermique (MWh),Nucléaire (MWh),Eolien (MWh),Solaire (MWh),Hydraulique (MWh),Bioénergies (MWh),TMin (°C),TMax (°C),TMoy (°C),Vitesse du vent à 100m (m/s),Rayonnement solaire global (W/m2)
0,2016-01-01 00:00:00+00:00,11,Île-de-France,199592.00,7386.50,0.0,191.50,27.50,235.50,3545.50,3.30,8.76,6.03,8.842857,44.570000
1,2016-01-01 00:00:00+00:00,24,Centre-Val de Loire,51985.50,1688.00,271526.5,6637.50,195.50,24.00,1190.50,1.52,10.73,6.12,9.200000,41.425714
2,2016-01-01 00:00:00+00:00,27,Bourgogne-Franche-Comté,56191.50,2677.50,0.0,2279.00,244.50,1009.00,412.00,2.22,9.52,5.87,6.178571,43.897143
3,2016-01-01 00:00:00+00:00,28,Normandie,77430.50,8127.00,152274.5,5268.50,52.50,394.00,1174.50,2.78,9.40,6.09,10.808571,23.730000
4,2016-01-01 00:00:00+00:00,32,Hauts-de-France,131545.50,12886.00,125341.0,17252.00,116.50,52.50,2965.00,1.72,7.72,4.72,8.911429,37.291429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33559,2023-08-28 00:00:00+00:00,53,Bretagne,68881.00,371.75,0.0,4388.75,1892.25,890.25,0.00,13.60,20.15,16.88,5.985000,183.160000
33560,2023-08-28 00:00:00+00:00,75,Nouvelle-Aquitaine,82677.25,1608.00,128768.5,6371.00,18697.00,1664.25,100.25,14.87,23.71,19.29,4.658750,203.776250
33561,2023-08-28 00:00:00+00:00,76,Occitanie,99470.50,159.25,0.0,24095.75,14924.75,20911.50,4284.75,15.55,24.15,19.85,5.816250,207.128750
33562,2023-08-28 00:00:00+00:00,84,Auvergne-Rhône-Alpes,148325.25,854.25,187631.0,8314.00,5786.25,62404.00,951.75,12.85,18.23,15.54,3.357500,168.930000
33563,2023-08-28 00:00:00+00:00,93,Provence-Alpes-Côte d'Azur,90799.00,13318.00,0.0,1570.25,8339.50,14863.25,1736.25,15.97,21.80,18.88,5.107500,214.223750

##7/Ajouter des variables temporelles

In [63]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import holidays

# Supposons que df_full_filtered est déjà défini et que la colonne 'Date' est au format datetime

# Assurez-vous que la colonne 'Date' est au format datetime
df_full_filtered['Date'] = pd.to_datetime(df_full_filtered['Date'])

# Ajouter des variables temporelles
df_full_filtered['Jour'] = df_full_filtered['Date'].dt.day
df_full_filtered['Mois'] = df_full_filtered['Date'].dt.month
df_full_filtered['Année'] = df_full_filtered['Date'].dt.year
df_full_filtered['Semaine_de_l_année'] = df_full_filtered['Date'].dt.isocalendar().week
df_full_filtered['Jour_de_la_semaine'] = df_full_filtered['Date'].dt.dayofweek  # 0 = Lundi, 6 = Dimanche

# Ajouter une colonne pour les jours fériés
fr_holidays = holidays.France(years=[2016, 2023])  # Créer un objet pour les jours fériés en France
df_full_filtered['Jour_férié'] = df_full_filtered['Date'].dt.date.isin(fr_holidays).astype(int)

# Ajout de transformations sinus et cosinus pour la semaine de l'année
df_full_filtered['Semaine_sin'] = np.sin(2 * np.pi * df_full_filtered['Semaine_de_l_année'] / 52)
df_full_filtered['Semaine_cos'] = np.cos(2 * np.pi * df_full_filtered['Semaine_de_l_année'] / 52)

# Représentation trigonométrique pour "Jour" (1 à 31) : sin et cos
df_full_filtered['Jour_sin'] = np.sin(2 * np.pi * df_full_filtered['Jour'] / 31)
df_full_filtered['Jour_cos'] = np.cos(2 * np.pi * df_full_filtered['Jour'] / 31)

# Représentation trigonométrique pour "Mois" (1 à 12) : sin et cos
df_full_filtered['Mois_sin'] = np.sin(2 * np.pi * df_full_filtered['Mois'] / 12)
df_full_filtered['Mois_cos'] = np.cos(2 * np.pi * df_full_filtered['Mois'] / 12)

# Vérifiez les premières lignes de df_full_filtered pour vous assurer que tout est correct
print(df_full_filtered.head())

<ipython-input-63-cfaa4144ca73>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Date'] = pd.to_datetime(df_full_filtered['Date'])
<ipython-input-63-cfaa4144ca73>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Jour'] = df_full_filtered['Date'].dt.day
<ipython-input-63-cfaa4144ca73>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Mois'] = df_full_filtered['Date'].dt.month
<ipython-input-63-cfaa4144ca73>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Année'] = df_full_filtered['Date'].dt.year
<ipython-input-63-cfaa4144ca73>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Semaine_de_l_année'] = df_full_filtered['Date'].dt.isocalendar().week
<ipython-input-63-cfaa4144ca73>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Jour_de_la_semaine'] = df_full_filtered['Date'].dt.dayofweek  # 0 = Lundi, 6 = Dimanche

                       Date Code INSEE région                   Région  \
0 2016-01-01 00:00:00+00:00                11            Île-de-France
1 2016-01-01 00:00:00+00:00                24      Centre-Val de Loire
2 2016-01-01 00:00:00+00:00                27  Bourgogne-Franche-Comté
3 2016-01-01 00:00:00+00:00                28                Normandie
4 2016-01-01 00:00:00+00:00                32          Hauts-de-France

   Consommation (MWh)  Thermique (MWh)  Nucléaire (MWh)  Eolien (MWh)  \
0            199592.0           7386.5              0.0         191.5
1             51985.5           1688.0         271526.5        6637.5
2             56191.5           2677.5              0.0        2279.0
3             77430.5           8127.0         152274.5        5268.5
4            131545.5          12886.0         125341.0       17252.0

   Solaire (MWh)  Hydraulique (MWh)  Bioénergies (MWh)  ...  Année  \
0           27.5              235.5             3545.5  ...   2016
1          195.5               24.0             1190.5  ...   2016
2          244.5             1009.0              412.0  ...   2016
3           52.5              394.0             1174.5  ...   2016
4          116.5               52.5             2965.0  ...   2016

   Semaine_de_l_année  Jour_de_la_semaine  Jour_férié  Semaine_sin  \
0                  53                   4           1     0.120537
1                  53                   4           1     0.120537
2                  53                   4           1     0.120537
3                  53                   4           1     0.120537
4                  53                   4           1     0.120537

   Semaine_cos  Jour_sin  Jour_cos  Mois_sin  Mois_cos
0     0.992709  0.201299   0.97953       0.5  0.866025
1     0.992709  0.201299   0.97953       0.5  0.866025
2     0.992709  0.201299   0.97953       0.5  0.866025
3     0.992709  0.201299   0.97953       0.5  0.866025
4     0.992709  0.201299   0.97953       0.5  0.866025

[5 rows x 27 columns]

<ipython-input-63-cfaa4144ca73>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Jour_férié'] = df_full_filtered['Date'].dt.date.isin(fr_holidays).astype(int)
<ipython-input-63-cfaa4144ca73>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Semaine_sin'] = np.sin(2 * np.pi * df_full_filtered['Semaine_de_l_année'] / 52)
<ipython-input-63-cfaa4144ca73>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Semaine_cos'] = np.cos(2 * np.pi * df_full_filtered['Semaine_de_l_année'] / 52)
<ipython-input-63-cfaa4144ca73>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Jour_sin'] = np.sin(2 * np.pi * df_full_filtered['Jour'] / 31)
<ipython-input-63-cfaa4144ca73>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Jour_cos'] = np.cos(2 * np.pi * df_full_filtered['Jour'] / 31)
<ipython-input-63-cfaa4144ca73>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Mois_sin'] = np.sin(2 * np.pi * df_full_filtered['Mois'] / 12)
<ipython-input-63-cfaa4144ca73>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Mois_cos'] = np.cos(2 * np.pi * df_full_filtered['Mois'] / 12)

In [64]:
# Enlever la partie horaire de la colonne 'Date'
df_full_filtered['Date'] = df_full_filtered['Date'].dt.date

<ipython-input-64-7ced20b71abd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Date'] = df_full_filtered['Date'].dt.date

In [65]:
print(df_full_filtered. head())

         Date Code INSEE région                   Région  Consommation (MWh)  \
0  2016-01-01                11            Île-de-France            199592.0
1  2016-01-01                24      Centre-Val de Loire             51985.5
2  2016-01-01                27  Bourgogne-Franche-Comté             56191.5
3  2016-01-01                28                Normandie             77430.5
4  2016-01-01                32          Hauts-de-France            131545.5

   Thermique (MWh)  Nucléaire (MWh)  Eolien (MWh)  Solaire (MWh)  \
0           7386.5              0.0         191.5           27.5
1           1688.0         271526.5        6637.5          195.5
2           2677.5              0.0        2279.0          244.5
3           8127.0         152274.5        5268.5           52.5
4          12886.0         125341.0       17252.0          116.5

   Hydraulique (MWh)  Bioénergies (MWh)  ...  Année  Semaine_de_l_année  \
0              235.5             3545.5  ...   2016                  53
1               24.0             1190.5  ...   2016                  53
2             1009.0              412.0  ...   2016                  53
3              394.0             1174.5  ...   2016                  53
4               52.5             2965.0  ...   2016                  53

   Jour_de_la_semaine  Jour_férié  Semaine_sin  Semaine_cos  Jour_sin  \
0                   4           1     0.120537     0.992709  0.201299
1                   4           1     0.120537     0.992709  0.201299
2                   4           1     0.120537     0.992709  0.201299
3                   4           1     0.120537     0.992709  0.201299
4                   4           1     0.120537     0.992709  0.201299

   Jour_cos  Mois_sin  Mois_cos
0   0.97953       0.5  0.866025
1   0.97953       0.5  0.866025
2   0.97953       0.5  0.866025
3   0.97953       0.5  0.866025
4   0.97953       0.5  0.866025

[5 rows x 27 columns]

In [66]:
df_full_filtered.columns

Index(['Date', 'Code INSEE région', 'Région', 'Consommation (MWh)',
       'Thermique (MWh)', 'Nucléaire (MWh)', 'Eolien (MWh)', 'Solaire (MWh)',
       'Hydraulique (MWh)', 'Bioénergies (MWh)', 'TMin (°C)', 'TMax (°C)',
       'TMoy (°C)', 'Vitesse du vent à 100m (m/s)',
       'Rayonnement solaire global (W/m2)', 'Jour', 'Mois', 'Année',
       'Semaine_de_l_année', 'Jour_de_la_semaine', 'Jour_férié', 'Semaine_sin',
       'Semaine_cos', 'Jour_sin', 'Jour_cos', 'Mois_sin', 'Mois_cos'],
      dtype='object')

##8/ Ajout de la variable Loi énergétique 2019

In [67]:


# Définir la date de la loi (8 novembre 2019)
date_loi = pd.to_datetime('2019-11-08')

# Convertir la colonne 'Date' en datetime.date
df_full_filtered['Date'] = pd.to_datetime(df_full_filtered['Date']).dt.date

# Comparer avec la date de la loi
date_loi_date = date_loi.date()

# Ajouter la colonne 'Loi energie climat 2019' avec True/False
df_full_filtered['Loi energie climat 2019'] = df_full_filtered['Date'] >= date_loi_date

<ipython-input-67-1d60725d7d1b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Date'] = pd.to_datetime(df_full_filtered['Date']).dt.date
<ipython-input-67-1d60725d7d1b>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_full_filtered['Loi energie climat 2019'] = df_full_filtered['Date'] >= date_loi_date

In [68]:
df_full_filtered

,Date,Code INSEE région,Région,Consommation (MWh),Thermique (MWh),Nucléaire (MWh),Eolien (MWh),Solaire (MWh),Hydraulique (MWh),Bioénergies (MWh),...,Semaine_de_l_année,Jour_de_la_semaine,Jour_férié,Semaine_sin,Semaine_cos,Jour_sin,Jour_cos,Mois_sin,Mois_cos,Loi energie climat 2019
0,2016-01-01,11,Île-de-France,199592.00,7386.50,0.0,191.50,27.50,235.50,3545.50,...,53,4,1,0.120537,0.992709,0.201299,0.979530,0.500000,0.866025,False
1,2016-01-01,24,Centre-Val de Loire,51985.50,1688.00,271526.5,6637.50,195.50,24.00,1190.50,...,53,4,1,0.120537,0.992709,0.201299,0.979530,0.500000,0.866025,False
2,2016-01-01,27,Bourgogne-Franche-Comté,56191.50,2677.50,0.0,2279.00,244.50,1009.00,412.00,...,53,4,1,0.120537,0.992709,0.201299,0.979530,0.500000,0.866025,False
3,2016-01-01,28,Normandie,77430.50,8127.00,152274.5,5268.50,52.50,394.00,1174.50,...,53,4,1,0.120537,0.992709,0.201299,0.979530,0.500000,0.866025,False
4,2016-01-01,32,Hauts-de-France,131545.50,12886.00,125341.0,17252.00,116.50,52.50,2965.00,...,53,4,1,0.120537,0.992709,0.201299,0.979530,0.500000,0.866025,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33559,2023-08-28,53,Bretagne,68881.00,371.75,0.0,4388.75,1892.25,890.25,0.00,...,35,0,0,-0.885456,-0.464723,-0.571268,0.820763,-0.866025,-0.500000,True
33560,2023-08-28,75,Nouvelle-Aquitaine,82677.25,1608.00,128768.5,6371.00,18697.00,1664.25,100.25,...,35,0,0,-0.885456,-0.464723,-0.571268,0.820763,-0.866025,-0.500000,True
33561,2023-08-28,76,Occitanie,99470.50,159.25,0.0,24095.75,14924.75,20911.50,4284.75,...,35,0,0,-0.885456,-0.464723,-0.571268,0.820763,-0.866025,-0.500000,True
33562,2023-08-28,84,Auvergne-Rhône-Alpes,148325.25,854.25,187631.0,8314.00,5786.25,62404.00,951.75,...,35,0,0,-0.885456,-0.464723,-0.571268,0.820763,-0.866025,-0.500000,True
33563,2023-08-28,93,Provence-Alpes-Côte d'Azur,90799.00,13318.00,0.0,1570.25,8339.50,14863.25,1736.25,...,35,0,0,-0.885456,-0.464723,-0.571268,0.820763,-0.866025,-0.500000,True

##*9*/Exporter le df_full

In [69]:
# Exporter le DataFrame df_full en tant que fichier CSV
df_full_filtered.to_csv('/content/drive/MyDrive/Colab_data_projet_ML/df_final_ML2.csv', index=False)